// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutoDrive.h"
#include "Commands/Autonomous.h"
#include "Commands/ConveyorOff.h"
#include "Commands/ConveyorOn.h"
#include "Commands/DelayBeforeShoot.h"
#include "Commands/IntakeOff.h"
#include "Commands/IntakeOn.h"
#include "Commands/Shift.h"
#include "Commands/ShooterOff.h"
#include "Commands/ShooterOn.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	driver = new Joystick(1);
	
	dButtonA = new JoystickButton(driver, 1);
	dButtonA->WhileHeld(new ConveyorOn());
	dButtonLb = new JoystickButton(driver, 11);
	dButtonLb->WhileHeld(new IntakeOn());
	dButtonRb = new JoystickButton(driver, 12);
	dButtonRb->WhileHeld(new ShooterOn());
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("ShooterOn", new ShooterOn());
	SmartDashboard::PutData("ShooterOff", new ShooterOff());
	SmartDashboard::PutData("IntakeOn", new IntakeOn());
	SmartDashboard::PutData("IntakeOff", new IntakeOff());
	SmartDashboard::PutData("ConveyorOn", new ConveyorOn());
	SmartDashboard::PutData("ConveyorOff", new ConveyorOff());
	SmartDashboard::PutData("Shift", new Shift());
	SmartDashboard::PutData("Autonomous", new Autonomous());
	SmartDashboard::PutData("DelayBeforeShoot", new DelayBeforeShoot());
	SmartDashboard::PutData("AutoDrive", new AutoDrive());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getDriver() {
	return driver;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
