// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
CANJaguar* RobotMap::shooterShooter1 = NULL;
CANJaguar* RobotMap::shooterShooter2 = NULL;
CANJaguar* RobotMap::intakeIntake1 = NULL;
CANJaguar* RobotMap::conveyorConveyor1 = NULL;
DoubleSolenoid* RobotMap::shifterShifter1 = NULL;
CANJaguar* RobotMap::chassisFrontLeft = NULL;
CANJaguar* RobotMap::chassisFrontRight = NULL;
CANJaguar* RobotMap::chassisRearLeft = NULL;
CANJaguar* RobotMap::chassisRearRight = NULL;
RobotDrive* RobotMap::chassisRobotDrive41 = NULL;
Encoder* RobotMap::chassisQuadratureEncoder1 = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	shooterShooter1 = new CANJaguar(7);
	
	
	shooterShooter2 = new CANJaguar(8);
	
	
	intakeIntake1 = new CANJaguar(11);
	
	
	conveyorConveyor1 = new CANJaguar(12);
	
	
	shifterShifter1 = new DoubleSolenoid(1, 1, 2);      
	
	
	chassisFrontLeft = new CANJaguar(2);
	
	
	chassisFrontRight = new CANJaguar(4);
	
	
	chassisRearLeft = new CANJaguar(3);
	
	
	chassisRearRight = new CANJaguar(5);
	
	
	chassisRobotDrive41 = new RobotDrive(chassisFrontLeft, chassisRearLeft,
              chassisFrontRight, chassisRearRight);
	
	chassisRobotDrive41->SetSafetyEnabled(true);
        chassisRobotDrive41->SetExpiration(0.1);
        chassisRobotDrive41->SetSensitivity(0.5);
        chassisRobotDrive41->SetMaxOutput(1.0);
	chassisQuadratureEncoder1 = new Encoder(1, 1, 1, 2, false, Encoder::k4X);
	lw->AddSensor("Chassis", "Quadrature Encoder 1", chassisQuadratureEncoder1);
	chassisQuadratureEncoder1->SetDistancePerPulse(1.0);
        chassisQuadratureEncoder1->SetPIDSourceParameter(Encoder::kRate);
        chassisQuadratureEncoder1->Start();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
